const en = {
  shapeLabels: {
    wobbi: 'Wobbi',
    ghost: 'Ghost',
    circle: 'Circle',
    'rounded-square': 'Rounded square',
    cloud: 'Cloud',
    drop: 'Drop',
    oval: 'Oval',
    egg: 'Egg',
  },
  eyeLabels: {
    classic: 'Big eyes',
    glossy: 'Glossy',
    round: 'Round',
    capsules: 'Capsules',
    dots: 'Dots',
    asymmetric: 'Asymmetric',
    pixel: 'Pixel',
    sleepy: 'Sleepy',
    angry: 'Angled',
    'side-eye': 'Side eye',
    wink: 'Wink',
    money: 'Dollar eyes',
  },
  noseLabels: {
    none: 'None',
    dot: 'Small nose',
    round: 'Round nose',
    muzzle: 'Muzzle',
    moustache: 'Moustache',
    beak: 'Beak',
  },
  browLabels: {
    none: 'None',
    soft: 'Soft',
    straight: 'Straight',
    arched: 'Arched',
    worried: 'Worried',
  },
  mouthLabels: {
    none: 'None',
    smile: 'Smile',
    open: 'Open',
    tooth: 'Two teeth',
    small: 'Small line',
    grin: 'Big smile',
    pout: 'Pout',
    fangs: 'Fangs',
  },
  headLabels: {
    none: 'None',
    tuft: 'Tuft',
    curl: 'Curl',
    'bunny-ears': 'Bunny ears',
    ears: 'Cat ears',
    'round-ears': 'Round ears',
    horns: 'Horns',
    halo: 'Halo',
  },
  accessoryLabels: {
    none: 'None',
    glasses: 'Glasses',
    sunglasses: 'Sunglasses',
    headphones: 'Headphones',
    bowtie: 'Bow tie',
    monocle: 'Monocle',
    blush: 'Blush',
    freckles: 'Freckles',
    bandage: 'Bandage',
  },
  reactionLabels: {
    idle: 'Idle',
    happy: 'Happy',
    thinking: 'Thinking',
    surprised: 'Surprised',
    sad: 'Scared',
    error: 'Angry',
    success: 'Success',
    loading: 'Loading',
    sleeping: 'Sleeping',
    singing: 'Singing',
  },
};

const fr = {
  shapeLabels: {
    wobbi: 'Wobbi',
    ghost: 'Fantôme',
    circle: 'Rond',
    'rounded-square': 'Carré arrondi',
    cloud: 'Nuage',
    drop: 'Goutte',
    oval: 'Ovale',
    egg: 'Œuf',
  },
  eyeLabels: {
    classic: 'Grands yeux',
    glossy: 'Brillants',
    round: 'Ronds',
    capsules: 'Capsules',
    dots: 'Points',
    asymmetric: 'Asymétriques',
    pixel: 'Pixels',
    sleepy: 'Paupières',
    angry: 'Anguleux',
    'side-eye': 'De côté',
    wink: 'Clin d’œil',
    money: 'Dollars',
  },
  noseLabels: {
    none: 'Sans',
    dot: 'Petit nez',
    round: 'Nez rond',
    muzzle: 'Museau',
    moustache: 'Moustache',
    beak: 'Bec',
  },
  browLabels: {
    none: 'Sans',
    soft: 'Doux',
    straight: 'Droits',
    arched: 'Arquées',
    worried: 'Inquiets',
  },
  mouthLabels: {
    none: 'Sans',
    smile: 'Sourire',
    open: 'Ouverte',
    tooth: 'Deux dents',
    small: 'Petit trait',
    grin: 'Grand sourire',
    pout: 'Moue',
    fangs: 'Crocs',
  },
  headLabels: {
    none: 'Sans',
    tuft: 'Mèche',
    curl: 'Boucle',
    'bunny-ears': 'Oreilles de lapin',
    ears: 'Oreilles de chat',
    'round-ears': 'Oreilles rondes',
    horns: 'Cornes',
    halo: 'Auréole',
  },
  accessoryLabels: {
    none: 'Sans',
    glasses: 'Lunettes',
    sunglasses: 'Lunettes de soleil',
    headphones: 'Casque',
    bowtie: 'Nœud papillon',
    monocle: 'Monocle',
    blush: 'Joues roses',
    freckles: 'Taches de rousseur',
    bandage: 'Pansement',
  },
  reactionLabels: {
    idle: 'Repos',
    happy: 'Joie',
    thinking: 'Réflexion',
    surprised: 'Surprise',
    sad: 'Peur',
    error: 'Colère',
    success: 'Réussite',
    loading: 'Attente',
    sleeping: 'Sommeil',
    singing: 'Chant',
  },
};

export function catalog(locale) {
  return locale === 'fr' ? fr : en;
}

export const palette = ['#111218', '#ffffff', '#9270ff', '#61a9ff', '#ffcc45'];
