import {titleCase} from '../ui/labels.js';
import {Check} from 'lucide-react';
import {PRESETS,resolveMascot} from '../../packages/registry/index.js';
import {SHAPES,EYES,createConfig} from '../../packages/core/config.js';
import {Mascot} from '../mascot/Mascot.jsx';
import {Field,Range,Segmented} from '../ui/Controls.jsx';
const colors=['#9775fa','#17171c','#ffffff','#f03f52','#ff9c38','#4999ef','#30b966'];
function EyesIcon({type}) {return <svg viewBox="0 0 44 32" width="38" height="29" aria-hidden="true">{type==='sleepy'?<path d="M5 12h13a6.5 6.5 0 0 1-13 0M26 12h13a6.5 6.5 0 0 1-13 0" fill="currentColor"/>:type==='angry'?<path d="m5 10 13 6q-2 11-10 4zm34 0-13 6q2 11 10 4z" fill="currentColor"/>:<><ellipse cx="12" cy="16" rx={type==='dots'?5:7} ry="10" fill="currentColor"/><ellipse cx="32" cy="16" rx={type==='dots'?5:7} ry="10" fill="currentColor"/>{type==='classic'&&<><circle cx="14" cy="12" r="2" fill="var(--surface)"/><circle cx="34" cy="12" r="2" fill="var(--surface)"/></>}</>}</svg>;}
export function DesignPanel({config,patch,onPreset}) {
 return <div className="design-controls panel-body">
  <section className="control-section presets"><div className="section-heading"><h2>Presets</h2><span>Start with a buddy</span></div><div className="preset-grid">{PRESETS.map(p=><button className="preset-button" key={p.slug} aria-label={`Preset ${p.label}`} aria-pressed={config.preset===p.slug} onClick={()=>onPreset(resolveMascot(p.slug))}><span className="preset-art"><Mascot config={resolveMascot(p.slug)} size={58} playing={false}/>{config.preset===p.slug&&<Check size={11} className="selection-check"/>}</span><span>{p.label}</span></button>)}</div></section>
  <section className="control-section"><h2>Shape</h2><div className="shape-options">{SHAPES.map(shape=><button title={titleCase(shape)} key={shape} aria-label={`Shape ${titleCase(shape)}`} aria-pressed={config.shape===shape} onClick={()=>patch({shape})}><Mascot config={createConfig({shape,color:'#353641',outlineWidth:0,mouth:'none'})} size={38} playing={false}/></button>)}</div></section>
  <section className="control-section"><h2>Eyes</h2><div className="eyes-options">{EYES.map(eyes=><button key={eyes} title={titleCase(eyes)} aria-label={`Eyes ${titleCase(eyes)}`} aria-pressed={config.eyes===eyes} onClick={()=>patch({eyes})}><EyesIcon type={eyes}/></button>)}</div></section>
  <section className="control-section"><div className="inline-field"><h2>Mouth</h2><select aria-label="Mouth" value={config.mouth} onChange={e=>patch({mouth:e.target.value})}><option value="none">None</option><option value="smile">Smile</option><option value="small">Small</option></select></div></section>
  <section className="control-section"><h2>Colors</h2><div className="swatches">{colors.map(color=><button key={color} style={{background:color}} aria-label={`Body ${color}`} aria-pressed={config.color===color} onClick={()=>patch({color})}>{config.color===color&&<Check size={14} color={color==='#ffffff'?'#17171c':'#fff'}/>}</button>)}</div><div className="color-fields"><Field label="Body"><input type="color" aria-label="Body color" value={config.color} onChange={e=>patch({color:e.target.value})}/></Field><Field label="Eyes"><input type="color" aria-label="Eye color" value={config.eyeColor} onChange={e=>patch({eyeColor:e.target.value})}/></Field><Field label="Outline"><input type="color" aria-label="Outline color" value={config.outlineColor} onChange={e=>patch({outlineColor:e.target.value})}/></Field></div></section>
  <section className="control-section"><Range label="Outline width" value={config.outlineWidth} min={0} max={16} unit=" px" onChange={outlineWidth=>patch({outlineWidth})}/></section>
  <section className="control-section"><div className="section-heading"><h2>Background</h2><input type="color" aria-label="Background color" value={config.background.color} onChange={e=>patch({background:{...config.background,color:e.target.value}})}/></div><Segmented label="Background type" value={config.background.type} options={['solid','gradient','transparent']} onChange={type=>patch({background:{...config.background,type}})}/></section>
  <section className="control-section"><Range label="Size" value={config.size} min={48} max={512} step={8} unit=" px" onChange={size=>patch({size})}/></section>
 </div>;
}

