import {it,expect} from 'vitest';
import {render,screen,within,fireEvent} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from '../../src/App.jsx';
const mainMascot=()=>within(screen.getByTestId('main-preview')).getByRole('img');
it('customizes preset, shape, eyes, colors, outline, background and size live',async()=>{
 const user=userEvent.setup();render(<App/>);
 await user.click(screen.getByRole('button',{name:'Preset Blinky'}));
 expect(mainMascot().querySelector('[data-part="body"]')).toHaveAttribute('fill','#f03f52');
 await user.click(screen.getByRole('button',{name:'Shape Circle'}));
 await user.click(screen.getByRole('button',{name:'Eyes Dots'}));
 expect(mainMascot().querySelector('[data-part="body"]')).toHaveAttribute('data-shape','circle');
 expect(mainMascot().querySelector('[data-part="eyes"]')).toHaveAttribute('data-eyes','dots');
 fireEvent.change(screen.getByLabelText('Body color'),{target:{value:'#336699'}});
 fireEvent.change(screen.getByLabelText('Size'),{target:{value:'192'}});
 fireEvent.change(screen.getByLabelText('Outline width'),{target:{value:'12'}});
 await user.click(screen.getByRole('button',{name:'Transparent'}));
 expect(mainMascot()).toHaveAttribute('width','192');
 expect(mainMascot().querySelector('[data-part="body"]')).toHaveAttribute('fill','#336699');
 expect(mainMascot().querySelector('[data-part="body"]')).toHaveAttribute('stroke-width','12');
 expect(screen.getByTestId('mascot-stage')).toHaveAttribute('data-background','transparent');
});
it('selects reactions and shows eight views of the same edited mascot',async()=>{
 const user=userEvent.setup();render(<App/>);
 await user.click(screen.getByRole('button',{name:'Reaction Happy'}));
 expect(mainMascot()).toHaveAttribute('data-state','happy');
 await user.click(screen.getByRole('tab',{name:'Grid',exact:true}));
 expect(within(screen.getByTestId('reaction-grid')).getAllByRole('img')).toHaveLength(8);
 await user.click(screen.getByRole('tab',{name:'Preview',exact:true}));
 expect(mainMascot()).toHaveAttribute('data-state','happy');
});
it('configures ordered motion and controls playback',async()=>{
 const user=userEvent.setup();render(<App/>);
 await user.click(screen.getByRole('tab',{name:'Motion',exact:true}));
 await user.selectOptions(screen.getByLabelText('Reaction to edit'),'happy');
 expect(mainMascot()).toHaveAttribute('data-state','happy');
 fireEvent.change(screen.getByLabelText('Duration'),{target:{value:'1200'}});
 fireEvent.change(screen.getByLabelText('Intensity'),{target:{value:'80'}});
 await user.click(screen.getByRole('button',{name:'Once',exact:true}));
 await user.click(screen.getByRole('switch',{name:'Bounce'}));
 expect(screen.getByRole('switch',{name:'Bounce'})).toHaveAttribute('aria-checked','false');
 await user.click(screen.getByRole('button',{name:'Move Tilt up'}));
 const rows=screen.getAllByTestId('movement-row');expect(rows[1]).toHaveTextContent('Tilt');
 await user.selectOptions(screen.getByLabelText('Movement to add'),'shake');
 await user.click(screen.getByRole('button',{name:'Add movement'}));
 expect(screen.getByRole('switch',{name:'Shake'})).toBeInTheDocument();
 await user.click(screen.getByRole('button',{name:'Play',exact:true}));
 expect(screen.getByRole('switch',{name:'Auto play'})).toHaveAttribute('aria-checked','true');
 await user.click(screen.getByRole('button',{name:'Replay',exact:true}));
 expect(screen.getByLabelText('Duration')).toHaveValue('1200');
});
it('shows real export files and copies command and individual usage snippets',async()=>{
 const user=userEvent.setup();render(<App/>);
 await user.click(screen.getByRole('button',{name:'Copy command',exact:true}));
 expect(await navigator.clipboard.readText()).toContain('node packages/cli/bin/wobbi.js add ghost-eye');
 await user.click(screen.getByRole('tab',{name:'Generated Files'}));
 expect(screen.getByRole('button',{name:'View GhostEye.jsx'})).toBeInTheDocument();
 await user.click(screen.getByRole('button',{name:'View GhostEye.jsx'}));
 expect(screen.getByTestId('source-code')).toHaveTextContent('export function GhostEye');
 await user.click(screen.getByRole('tab',{name:'Usage',exact:true}));
 await user.click(screen.getByRole('button',{name:'Copy Change reaction'}));
 expect(await navigator.clipboard.readText()).toBe('<GhostEye state="thinking" />');
});
