name: Enhancement
description: Propose a focused improvement
title: '[Enhancement] '
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: User need
      description: Which user problem should this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
