name: Évolution
description: Proposer une amélioration ciblée
title: '[Évolution] '
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: Besoin
      description: Quel problème utilisateur faut-il résoudre ?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposition
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives envisagées
